name: "Deploy to Server"

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.19.0
      - name: "Build deployment code for standalone"
        env:
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
          dev_env_file: ${{ secrets.DEV_ENV_FILE }}
          frontend_local_dir: "./frontend/build/"
          frontend_remote_dir: "/var/www/tuina/public"
          backend_local_dir: "./backend/"
          backend_remote_dir: "/var/www/tuina/backend"
      - run: |
          npm install
          echo "$dev_env_file" > ./frontend/.env
          chmod 600 ./frontend/.env
          unset CI
          npm run build
          mkdir ~/.ssh
          echo "$remote_key" > ~/.ssh/id_tuina_deploy_key
          chmod 600 ~/.ssh/id_tuina_deploy_key
          rsync -azvr --delete -e "ssh -p ${remote_port} -i ~/.ssh/id_tuina_deploy_key -o StrictHostKeyChecking=no" ${frontend_local_dir} ${remote_user}@${remote_host}:${frontend_remote_dir}
          rsync -azvr --delete -e "ssh -p ${remote_port} -i ~/.ssh/id_tuina_deploy_key -o StrictHostKeyChecking=no" ${backend_local_dir} ${remote_user}@${remote_host}:${backend_remote_dir}
          rm ~/.ssh/id_tuina_deploy_key
      - run: |
          npm install
          echo "$dev_env_file" > ./frontend/.env
          chmod 600 ./frontend/.env
          unset CI
          npm run build
          mkdir ~/.ssh
          echo "$remote_key" > ~/.ssh/id_tuina_deploy_key
          chmod 600 ~/.ssh/id_tuina_deploy_key
          rsync -azvr --delete -e "ssh -p ${remote_port} -i ~/.ssh/id_tuina_deploy_key -o StrictHostKeyChecking=no" ${frontend_local_dir} ${remote_user}@${remote_host}:${frontend_remote_dir}
          rsync -azvr --delete -e "ssh -p ${remote_port} -i ~/.ssh/id_tuina_deploy_key -o StrictHostKeyChecking=no" ${backend_local_dir} ${remote_user}@${remote_host}:${backend_remote_dir}
          rm ~/.ssh/id_tuina_deploy_key
